// SPDX-License-Identifier: GPL-2.0

//! Generated chain-of-blocks load: a pure function of the run seed and the
//! load generation.
//!
//! Every step calls `ChainOfBlocks.append(payload)`
//! (workloads/tempo-dst/chain), from one sender in nonce order. The contract
//! links each payload to its stored head, so the writer never needs to know
//! the on-chain head: after a crash drops the transaction pool, the next
//! generation's appends simply extend whatever chain the node kept. The
//! oracle (`cob`) recovers payloads from receipts, so it does not need this
//! spec either; payloads are distinct per (seed, generation, step) only so
//! that a replayed or misplaced append is visible in the links.

use alloy_primitives::{keccak256, B256};

/// ChainOfBlocks' CREATE address: dev account 9's first transaction
/// (`chain/deploy.yaml`), distinct from the trie load's deployer.
pub const CONTRACT: &str = "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35";
/// Dev mnemonic index of the deployer and only writer.
const SENDER: u32 = 9;

/// Payload of step `step` of load generation `generation`.
pub fn payload(seed: u64, generation: u64, step: u64) -> B256 {
    let mut buf = [0u8; 24];
    buf[..8].copy_from_slice(&seed.to_be_bytes());
    buf[8..16].copy_from_slice(&generation.to_be_bytes());
    buf[16..].copy_from_slice(&step.to_be_bytes());
    keccak256(buf)
}

/// txgen spec for load generation `generation` (0 at branch start, one more
/// per node restart): `steps` appends in one sequence, so the single sender
/// keeps them in nonce order and submits them back-to-back.
pub fn spec(seed: u64, generation: u64, steps: usize) -> String {
    let mut out = format!(
        "# Generated by tempo-dst (cob_gen) for seed {seed}, load generation {generation}.\n\
         chain_id: 1337\n\
         accounts:\n  chain:\n    mnemonic: \"test test test test test test test test test test test junk\"\n    range: [{SENDER}, {}]\n\
         artifacts:\n  ChainOfBlocks:\n    abi: chain-of-blocks.json\n    bytecode: chain-of-blocks.json\n\
         templates:\n  append:\n    type: tempo\n    from: {{ pool: chain, select: {{ index: 0 }} }}\n    gas_limit: 5000000\n\
         \x20   max_fee_per_gas: 100000000000\n    max_priority_fee_per_gas: 1000000000\n\
         \x20   fee_token: \"0x20c0000000000000000000000000000000000000\"\n\
         \x20   call:\n      abi: ChainOfBlocks\n      function: append\n      args: []\n\
         sequences:\n  appends:\n    steps:\n",
        SENDER + 1
    );
    for i in 0..steps {
        let p = payload(seed, generation, i as u64);
        out.push_str(&format!(
            "      - {{ name: a{i}, template: append, with: {{ call: {{ to: \"{CONTRACT}\", args: [\"{p}\"] }} }} }}\n"
        ));
    }
    out.push_str("mix:\n  - { sequence: appends, weight: 1 }\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn payloads_are_distinct_per_seed_generation_and_step() {
        let a = payload(1, 0, 0);
        assert_eq!(a, payload(1, 0, 0));
        assert_ne!(a, payload(2, 0, 0));
        assert_ne!(a, payload(1, 1, 0));
        assert_ne!(a, payload(1, 0, 1));
    }

    #[test]
    fn spec_is_deterministic_per_generation() {
        let a = spec(3, 0, 20);
        assert_eq!(a, spec(3, 0, 20));
        assert_ne!(a, spec(3, 1, 20));
        assert_eq!(a.matches("template: append").count(), 20);
        assert!(a.contains(&payload(3, 0, 19).to_string()));
        assert!(a.contains("range: [9, 10]"));
    }
}
